title: ChooseaLicense.com.br - Licenças
relative_permalinks: false
markdown: redcarpet

rules:

  required:
    include-copyright:
      description: Inclua uma cópia da licença e aviso de direitos autorais com o código.
      label: Aviso de licença e direitos autorais
    document-changes: 
      description: Indicar alterações significativas feitas no código.
      label: Alterações no Código
    disclose-source:
      description: O código fonte deve ser disponibilizado ao distribuir o software. No caso da LPL, a fonte para a biblioteca (e não todo o programa) deve ser disponibilizada.
      label: Disponibilizar Fonte
    library-usage:
      description: A biblioteca pode ser usada dentro de um aplicativo não-open-source. 
      label: Uso de biblioteca
    rename: 
      description: Você deve alterar o nome do software se modificá-lo.
      label: Renomear

  permitted:
    commercial-use: 
      description: Este software e seus derivados podem ser utilizados para propósitos comerciais.
      label: Uso Comercial
    modifications: 
      description: Este software pode ser modificado.
      label: Modificação
    distribution: 
      description: Você pode distribuir este software.
      label: Distribuição
    sublicense: 
      description: Você pode conceder uma sub-licença para modificar e distribuir este software a terceiros não incluídos na licença.
      label: Sublicenciamento
    private-use: 
      description: Você pode utilizar e modificar o software sem distribuí-lo.
      label: Uso Privado
    patent-grant:
      description: Esta licença fornece uma concessão expressa de direitos de patente do contribuinte para o destinatário.
      label: Garantia de Patente

  forbidden:
    trademark-use:
      description: Embora isso possa estar implícito em todas as licenças, esta licença afirma explicitamente que você não pode usar os nomes, logotipos ou marcas dos contribuidores.
      label: Uso de Marca Registrada
    no-liability: 
      description: O software é fornecido sem garantias e o autor do software/dono da licença não pode ser responsabilizado por perdas e danos.
      label: Responsabilidade Legal
    no-sublicense: 
      description: Você não pode conceder uma sub-licença para modificar e distribuir este software a terceiros não incluídos na licença.
      label: Sublicenciamento
    modifications:
      description: Este software não pode ser modificado.
      label: Modificação
    distribution:
      description: Você não pode distribuir este software.
      label: Distribuição
    sublicense:
      description: Você não pode conceder uma sub-licença para modificar e distribuir este software a terceiros não incluídos na licença.
      label: Sublicenciamento

exclude:
  - CNAME
  - Gemfile*
  - script
